//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotpsBot.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CotpsBot.Resources.Lang.LangRes.en", typeof(LangRes_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing service not available.
        /// </summary>
        internal static string billing_service_not_available {
            get {
                return ResourceManager.GetString("billing_service_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing service not available. Restart bot manually..
        /// </summary>
        internal static string billing_svc_not_available_restart {
            get {
                return ResourceManager.GetString("billing_svc_not_available_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string bot_off {
            get {
                return ResourceManager.GetString("bot_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string bot_on {
            get {
                return ResourceManager.GetString("bot_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOT START.
        /// </summary>
        internal static string BOT_START {
            get {
                return ResourceManager.GetString("BOT START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOT STATUS.
        /// </summary>
        internal static string bot_status {
            get {
                return ResourceManager.GetString("bot_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOT STOP.
        /// </summary>
        internal static string BOT_STOP {
            get {
                return ResourceManager.GetString("BOT STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get data. Unstable Internet Connection.
        /// </summary>
        internal static string cant_get_data {
            get {
                return ResourceManager.GetString("cant_get_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your credentials and restart bot service.
        /// </summary>
        internal static string check_credentials_and_restart_bot {
            get {
                return ResourceManager.GetString("check_credentials_and_restart_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support if the error persists.
        /// </summary>
        internal static string contact_support_error_persist {
            get {
                return ResourceManager.GetString("contact_support_error_persist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS API Error.
        /// </summary>
        internal static string COTPS_API_Error {
            get {
                return ResourceManager.GetString("COTPS API Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in the COTPS API. Waiting to try again..
        /// </summary>
        internal static string cotps_api_error_waiting {
            get {
                return ResourceManager.GetString("cotps_api_error_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS API Unauthorized.
        /// </summary>
        internal static string COTPS_API_Unauthorized {
            get {
                return ResourceManager.GetString("COTPS API Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS Login Error.
        /// </summary>
        internal static string cotps_login_error {
            get {
                return ResourceManager.GetString("cotps_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS Bot Restart Error.
        /// </summary>
        internal static string cotps_restart_error {
            get {
                return ResourceManager.GetString("cotps_restart_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS Service.
        /// </summary>
        internal static string cotps_service {
            get {
                return ResourceManager.GetString("cotps_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS Bot Service is working.
        /// </summary>
        internal static string cotps_service_working {
            get {
                return ResourceManager.GetString("cotps_service_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTPS Service could not be restarted.
        /// </summary>
        internal static string cotps_svc_not_restarted {
            get {
                return ResourceManager.GetString("cotps_svc_not_restarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error confirming order.
        /// </summary>
        internal static string error_confirming_order {
            get {
                return ResourceManager.GetString("error_confirming_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to buy the COTPS service.
        /// </summary>
        internal static string error_trying_buy_cotps {
            get {
                return ResourceManager.GetString("error_trying_buy_cotps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE BALANCE.
        /// </summary>
        internal static string free_balance {
            get {
                return ResourceManager.GetString("free_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREEZE BALANCE.
        /// </summary>
        internal static string freeze_balance {
            get {
                return ResourceManager.GetString("freeze_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST RUN.
        /// </summary>
        internal static string last_run {
            get {
                return ResourceManager.GetString("last_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string no_internet_connection {
            get {
                return ResourceManager.GetString("no_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection. Unable to start bot and get account details..
        /// </summary>
        internal static string no_internet_tapped_inactive {
            get {
                return ResourceManager.GetString("no_internet_tapped_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection to get data. The bot still working waiting for connection to start operating again..
        /// </summary>
        internal static string no_internet_tapped_running {
            get {
                return ResourceManager.GetString("no_internet_tapped_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection to verify subscription.
        /// </summary>
        internal static string no_internet_verify_sub {
            get {
                return ResourceManager.GetString("no_internet_verify_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order could not be confirmed.
        /// </summary>
        internal static string order_not_confirmed {
            get {
                return ResourceManager.GetString("order_not_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string password_required {
            get {
                return ResourceManager.GetString("password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone and Password required.
        /// </summary>
        internal static string phone_password_required {
            get {
                return ResourceManager.GetString("phone_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        internal static string phone_required {
            get {
                return ResourceManager.GetString("phone_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember credentials.
        /// </summary>
        internal static string remember_credentials {
            get {
                return ResourceManager.GetString("remember_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team residual could not be obtained.
        /// </summary>
        internal static string residual_not_obtained {
            get {
                return ResourceManager.GetString("residual_not_obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual benefits could not be obtained.
        /// </summary>
        internal static string residual_not_obtained_details {
            get {
                return ResourceManager.GetString("residual_not_obtained_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting COTPS Bot.
        /// </summary>
        internal static string restarting_cotps_bot {
            get {
                return ResourceManager.GetString("restarting_cotps_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something was wrong.
        /// </summary>
        internal static string something_was_wrong {
            get {
                return ResourceManager.GetString("something_was_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the subscription to proceed.
        /// </summary>
        internal static string sub_complete_to_proceed {
            get {
                return ResourceManager.GetString("sub_complete_to_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription completed successfully.
        /// </summary>
        internal static string sub_completed_successfully {
            get {
                return ResourceManager.GetString("sub_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription has ended. Open the app and start the bot to renew it.
        /// </summary>
        internal static string sub_ended_open_to_renew {
            get {
                return ResourceManager.GetString("sub_ended_open_to_renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to verify the subscription.
        /// </summary>
        internal static string sub_verifying_error {
            get {
                return ResourceManager.GetString("sub_verifying_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription error.
        /// </summary>
        internal static string subscription_error {
            get {
                return ResourceManager.GetString("subscription_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL BALANCE.
        /// </summary>
        internal static string total_balance {
            get {
                return ResourceManager.GetString("total_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported device.
        /// </summary>
        internal static string unsupported_device {
            get {
                return ResourceManager.GetString("unsupported_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Internet connection to operate.
        /// </summary>
        internal static string waiting_internet_to_operate {
            get {
                return ResourceManager.GetString("waiting_internet_to_operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your COTPS Password.
        /// </summary>
        internal static string your_cotps_password {
            get {
                return ResourceManager.GetString("your_cotps_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your COTPS Phone.
        /// </summary>
        internal static string your_cotps_phone {
            get {
                return ResourceManager.GetString("your_cotps_phone", resourceCulture);
            }
        }
    }
}
