//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotpsBot.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CotpsBot.Resources.Lang.LangRes.es", typeof(LangRes_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de compra no disponible.
        /// </summary>
        internal static string billing_service_not_available {
            get {
                return ResourceManager.GetString("billing_service_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de facturación no disponible. Reinicie el bot manualmente..
        /// </summary>
        internal static string billing_svc_not_available_restart {
            get {
                return ResourceManager.GetString("billing_svc_not_available_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APAGADO.
        /// </summary>
        internal static string bot_off {
            get {
                return ResourceManager.GetString("bot_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCENDIDO.
        /// </summary>
        internal static string bot_on {
            get {
                return ResourceManager.GetString("bot_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAR BOT.
        /// </summary>
        internal static string BOT_START {
            get {
                return ResourceManager.GetString("BOT START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO DEL BOT.
        /// </summary>
        internal static string bot_status {
            get {
                return ResourceManager.GetString("bot_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETENER BOT.
        /// </summary>
        internal static string BOT_STOP {
            get {
                return ResourceManager.GetString("BOT STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden obtener datos. Conexión a Internet Inestable.
        /// </summary>
        internal static string cant_get_data {
            get {
                return ResourceManager.GetString("cant_get_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique sus credenciales y reinicie el bot.
        /// </summary>
        internal static string check_credentials_and_restart_bot {
            get {
                return ResourceManager.GetString("check_credentials_and_restart_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error iniciando sesión en COTPS.
        /// </summary>
        internal static string cotps_login_error {
            get {
                return ResourceManager.GetString("cotps_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reiniciando el bot de COTPS.
        /// </summary>
        internal static string cotps_restart_error {
            get {
                return ResourceManager.GetString("cotps_restart_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de COTPS.
        /// </summary>
        internal static string cotps_service {
            get {
                return ResourceManager.GetString("cotps_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El bot de COTPS está ejecutándose.
        /// </summary>
        internal static string cotps_service_working {
            get {
                return ResourceManager.GetString("cotps_service_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo reiniciar el servicio de COTPS.
        /// </summary>
        internal static string cotps_svc_not_restarted {
            get {
                return ResourceManager.GetString("cotps_svc_not_restarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al confirmar el pedido.
        /// </summary>
        internal static string error_confirming_order {
            get {
                return ResourceManager.GetString("error_confirming_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar comprar el servicio COTPS.
        /// </summary>
        internal static string error_trying_buy_cotps {
            get {
                return ResourceManager.GetString("error_trying_buy_cotps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALDO DE WALLET.
        /// </summary>
        internal static string free_balance {
            get {
                return ResourceManager.GetString("free_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESANDO.
        /// </summary>
        internal static string freeze_balance {
            get {
                return ResourceManager.GetString("freeze_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚLTIMA EJECUCIÓN.
        /// </summary>
        internal static string last_run {
            get {
                return ResourceManager.GetString("last_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conexión a Internet.
        /// </summary>
        internal static string no_internet_connection {
            get {
                return ResourceManager.GetString("no_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conexión a Internet para verificar la suscripción.
        /// </summary>
        internal static string no_internet_verify_sub {
            get {
                return ResourceManager.GetString("no_internet_verify_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo confirmar el pedido.
        /// </summary>
        internal static string order_not_confirmed {
            get {
                return ResourceManager.GetString("order_not_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere la contraseña.
        /// </summary>
        internal static string password_required {
            get {
                return ResourceManager.GetString("password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono y Contraseña son requeridos.
        /// </summary>
        internal static string phone_password_required {
            get {
                return ResourceManager.GetString("phone_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere el número de teléfono.
        /// </summary>
        internal static string phone_required {
            get {
                return ResourceManager.GetString("phone_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar credenciales.
        /// </summary>
        internal static string remember_credentials {
            get {
                return ResourceManager.GetString("remember_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener el residual del equipo.
        /// </summary>
        internal static string residual_not_obtained {
            get {
                return ResourceManager.GetString("residual_not_obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener los beneficios residuales.
        /// </summary>
        internal static string residual_not_obtained_details {
            get {
                return ResourceManager.GetString("residual_not_obtained_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciando bot de COTPS.
        /// </summary>
        internal static string restarting_cotps_bot {
            get {
                return ResourceManager.GetString("restarting_cotps_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal.
        /// </summary>
        internal static string something_was_wrong {
            get {
                return ResourceManager.GetString("something_was_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete la suscripción para continuar.
        /// </summary>
        internal static string sub_complete_to_proceed {
            get {
                return ResourceManager.GetString("sub_complete_to_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscripción completada con éxito.
        /// </summary>
        internal static string sub_completed_successfully {
            get {
                return ResourceManager.GetString("sub_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su suscripción ha finalizado. Abra la aplicación e inicie el bot para renovarlo..
        /// </summary>
        internal static string sub_ended_open_to_renew {
            get {
                return ResourceManager.GetString("sub_ended_open_to_renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar verificar la suscripción.
        /// </summary>
        internal static string sub_verifying_error {
            get {
                return ResourceManager.GetString("sub_verifying_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de suscripción.
        /// </summary>
        internal static string subscription_error {
            get {
                return ResourceManager.GetString("subscription_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVOS TOTALES.
        /// </summary>
        internal static string total_balance {
            get {
                return ResourceManager.GetString("total_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo no compatible.
        /// </summary>
        internal static string unsupported_device {
            get {
                return ResourceManager.GetString("unsupported_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando conexión a Internet para operar.
        /// </summary>
        internal static string waiting_internet_to_operate {
            get {
                return ResourceManager.GetString("waiting_internet_to_operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña de COTPS.
        /// </summary>
        internal static string your_cotps_password {
            get {
                return ResourceManager.GetString("your_cotps_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono de COTPS.
        /// </summary>
        internal static string your_cotps_phone {
            get {
                return ResourceManager.GetString("your_cotps_phone", resourceCulture);
            }
        }
    }
}
